# Generated by Django 4.2.2 on 2023-06-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce3', '0002_remove_detallesventas_id_sxm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
