# Generated by Django 4.2.2 on 2023-06-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce3', '0004_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosmedicos',
            name='Clave_UM',
        ),
        migrations.RemoveField(
            model_name='usuariosmedicos',
            name='Email_UM',
        ),
        migrations.AlterField(
            model_name='usuariosmedicos',
            name='Matricula_UM',
            field=models.CharField(blank=True, default='Matricula_UM', max_length=8),
        ),
    ]
