# Generated by Django 4.2.2 on 2023-06-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce3', '0005_remove_usuariosmedicos_clave_um_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariospacientes',
            name='Celular_UP',
        ),
        migrations.RemoveField(
            model_name='usuariospacientes',
            name='Direccion_UP',
        ),
        migrations.RemoveField(
            model_name='usuariospacientes',
            name='Dni_UP',
        ),
        migrations.RemoveField(
            model_name='usuariospacientes',
            name='Localidad_UP',
        ),
    ]
