# Generated by Django 4.2.1 on 2023-05-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saldo_C', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Cuentas de usuarios',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoServicio_S', models.CharField(max_length=20)),
                ('Precio_S', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Descripcion_S', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Tipo de Servicios',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='TiposEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEstudio_TE', models.CharField(max_length=45)),
                ('Descripcion_TE', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Tipo de Estudio',
                'verbose_name_plural': 'TiposEstudios',
                'db_table': 'TiposEstudios',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaVenta_V', models.DateField(auto_now_add=True)),
                ('TotalVenta_V', models.DecimalField(decimal_places=2, max_digits=18)),
                ('id_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.cuentas')),
            ],
            options={
                'verbose_name': 'Ventas a Cuentas',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='UsuariosPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_UP', models.CharField(max_length=45)),
                ('Apellido_UP', models.CharField(max_length=45)),
                ('Email_UP', models.CharField(max_length=45)),
                ('Clave_UP', models.CharField(max_length=45)),
                ('Celular_UP', models.CharField(blank=True, default='Celular_UP', max_length=45)),
                ('Direccion_UP', models.CharField(blank=True, default='Direccion_UP', max_length=100)),
                ('Localidad_UP', models.CharField(blank=True, default='Localidad_UP', max_length=45)),
                ('Dni_UP', models.CharField(blank=True, default='Dni_UP', max_length=8)),
                ('id_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.cuentas')),
            ],
            options={
                'verbose_name': 'Usuarios Pacientes',
                'verbose_name_plural': 'UsuariosPacientes',
                'db_table': 'UsuariosPacientes',
            },
        ),
        migrations.CreateModel(
            name='UsuariosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_UM', models.CharField(max_length=45)),
                ('Apellido_UM', models.CharField(max_length=45)),
                ('Email_UM', models.CharField(max_length=45)),
                ('Clave_UM', models.CharField(max_length=45)),
                ('Celular_UM', models.CharField(blank=True, default='Celular_UM', max_length=45)),
                ('Direccion_UM', models.CharField(blank=True, default='Direccion_UM', max_length=100)),
                ('Localidad_UM', models.CharField(blank=True, default='Localidad_UM', max_length=45)),
                ('Dni_UM', models.CharField(blank=True, default='Dni_UM', max_length=8)),
                ('Matricula_UM', models.CharField(blank=True, default='Mat_UM', max_length=8)),
                ('id_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.cuentas')),
            ],
            options={
                'verbose_name': 'Usuarios Medicos',
                'verbose_name_plural': 'UsuariosMedicos',
                'db_table': 'UsuariosMedicos',
            },
        ),
        migrations.CreateModel(
            name='ServiciosXMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_S', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.servicios')),
                ('id_UM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.usuariosmedicos')),
            ],
            options={
                'verbose_name': 'Servicio y Medico',
                'verbose_name_plural': 'ServiciosMedicos',
                'db_table': 'ServiciosXMedicos',
            },
        ),
        migrations.CreateModel(
            name='MedicosPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_UM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.usuariosmedicos')),
                ('id_UP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.usuariospacientes')),
            ],
            options={
                'verbose_name': 'Medicos Pacientes',
                'verbose_name_plural': 'MedicosPacientes',
                'db_table': 'MedicosPacientes',
            },
        ),
        migrations.CreateModel(
            name='HistorialesMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_HM', models.CharField(max_length=100)),
                ('id_MP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.medicospacientes')),
                ('id_TE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.tiposestudios')),
            ],
            options={
                'verbose_name': 'Hisrotial Medico Paciente Tipo Estudio',
                'verbose_name_plural': 'HistorialesMedicos',
                'db_table': 'HistorialesMedicos',
            },
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioServi_DV', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CantServi_DV', models.IntegerField()),
                ('id_SXM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.serviciosxmedicos')),
                ('id_V', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.ventas')),
            ],
            options={
                'verbose_name': 'Detalle y Venta',
                'verbose_name_plural': 'DetallesVentas',
                'db_table': 'DetallesVentas',
            },
        ),
    ]
