# Generated by Django 4.2.2 on 2023-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce3', '0005_alter_customuser_nombre_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Nombre_UP',
            field=models.CharField(blank=True, default='Nombre', max_length=45),
        ),
    ]
