# Generated by Django 4.2.2 on 2023-06-13 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce3', '0007_customuser_apellido_up_customuser_celular_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesventas',
            name='id_SXM',
        ),
        migrations.RemoveField(
            model_name='detallesventas',
            name='id_V',
        ),
        migrations.RemoveField(
            model_name='historialesmedicos',
            name='id_MP',
        ),
        migrations.RemoveField(
            model_name='historialesmedicos',
            name='id_TE',
        ),
        migrations.RemoveField(
            model_name='medicospacientes',
            name='id_UM',
        ),
        migrations.RemoveField(
            model_name='medicospacientes',
            name='id_UP',
        ),
        migrations.RemoveField(
            model_name='serviciosxmedicos',
            name='id_S',
        ),
        migrations.RemoveField(
            model_name='serviciosxmedicos',
            name='id_UM',
        ),
        migrations.RemoveField(
            model_name='usuariosmedicos',
            name='id_C',
        ),
        migrations.RemoveField(
            model_name='usuariospacientes',
            name='id_C',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_C',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_C',
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_S',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce3.servicios'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_UP',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cuentas',
        ),
        migrations.DeleteModel(
            name='DetallesVentas',
        ),
        migrations.DeleteModel(
            name='HistorialesMedicos',
        ),
        migrations.DeleteModel(
            name='MedicosPacientes',
        ),
        migrations.DeleteModel(
            name='ServiciosXMedicos',
        ),
        migrations.DeleteModel(
            name='TiposEstudios',
        ),
        migrations.DeleteModel(
            name='UsuariosMedicos',
        ),
        migrations.DeleteModel(
            name='UsuariosPacientes',
        ),
    ]
